# fly.toml app configuration file generated for ai-course-advisor on 2025-04-16T06:31:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ai-course-advisor'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
